21 may 2024
Deltares-research/tech-radar pull request #8
Opened 2024-05-24 09:06 UTC by deltamarnix

2024-05-24 09:37 UTC, joelvdberg requested changes

2024-05-24 09:37 UTC, joelvdberg commented on radar.csv
> +pip,Assess,tools,FALSE,"<p><strong><a href=""https://pip.pypa.io/en/stable/"">pip</a></strong> is the package installer for Python. You can use pip to install packages from the Python Package Index a
```suggestion
pip,Assess,tools,FALSE,"<p><strong><a href=""https://pip.pypa.io/en/stable/"">pip</a></strong> is the package installer for Python. You can use pip to install packages from the Python Package Index and other indexes.</p><p>Motivation: Deltares is using both Conda and Pip, depending on the types of packages. Pip cannot easily distribute binaries as Conda does. Pip is considered slow in dependency resolving. In a lot of project we now use Pixi, which uses uv under the hood to perform quick pip dependency resolving.</p>"
```

2024-05-24 09:37 UTC, joelvdberg commented on radar.csv
> +QGIS,Trial,platform,FALSE,"<p><strong><a href=""https://qgis.org/"">QGIS</a></strong> is a free and open-source cross-platform desktop geographic information system (GIS) application that supports vi
```suggestion
QGIS,Trial,platform,FALSE,"<p><strong><a href=""https://qgis.org/"">QGIS</a></strong> is a free and open-source cross-platform desktop geographic information system (GIS) application that supports viewing, editing, and analysis of geospatial data.</p><p>Motivation: The PMT Hydrology and Hydrodynamics is writing user interface plugins for QGIS and is wondering if these kind of user interfaces are the way to go in the future. If so, we should be able to co-create with QGIS and influence their technical roadmap.</p>"
```

2024-05-24 09:37 UTC, joelvdberg commented on radar.csv
> +Dependabot,Trial,platforms,TRUE,"<p><strong><a href=""https://dependabot.com/"">Dependabot</a></strong> is a tool that automates dependency updates. It checks for updates to your dependencies every d
I had a hard time recalling what was meant with "Can we use custom repositories for update checking". Maybe this needs to made clearer:

```suggestion
Dependabot,Trial,platforms,TRUE,"<p><strong><a href=""https://dependabot.com/"">Dependabot</a></strong> is a tool that automates dependency updates. It checks for updates to your dependencies every day and opens a pull request when it finds an update. You can configure Dependabot to open pull requests immediately or after a certain number of days. There are also vulnerability checks in place.</p><p>Motivation: Dependabot comes for free with our Github subscription. It is useful, but does not work for all ecosystems and only works for Github repositories. Still it is useful to enable it where possible.</p><p>Question: Can dependabot check for updated packages in a privately hosted package repository?</p>"
```

2024-05-24 09:37 UTC, joelvdberg commented on radar.csv
> +Rust,Assess,languages-and-frameworks,TRUE,"<p><strong><a href=""https://www.rust-lang.org/"">Rust</a></strong> is a systems programming language that runs blazingly fast, prevents segfaults, and guar
If "Deltares would like to try out projects with this language", then shouldn't Rust be in quadrant _Trial_?

2024-05-24 10:53 UTC, deltamarnix commented on radar.csv
> +Rust,Assess,languages-and-frameworks,TRUE,"<p><strong><a href=""https://www.rust-lang.org/"">Rust</a></strong> is a systems programming language that runs blazingly fast, prevents segfaults, and guar
Depends on how we see it, we currently don't have any trials going on with this language.

2024-05-28 11:32 UTC, joelvdberg approved these changes

2024-05-28 11:33 UTC, merged