28 may 2024
Deltares-research/tech-radar pull request #9
Opened 2024-05-29 15:46 UTC by deltamarnix

Add information on the how and why for the tech radar.

@joelvdberg Can you help to publish this? I don't know how to run it locally or see if it looks good in any way.

2024-05-29 18:38 UTC, joelvdberg commented
> Add information on the how and why for the tech radar.
> 
> @joelvdberg Can you help to publish this? I don't know how to run it locally or see if it looks good in any way.

To run the radar locally, install Docker and build an image using the Dockerfile in the root dir. Then launch the container with e.g. the port 8080 routed to the container.

2024-06-07 11:00 UTC, joelvdberg requested changes

2024-06-07 11:00 UTC, joelvdberg commented on src/index.html
My compliments on the added descriptions. It's well-worded and clearly show our intention 👍

2024-06-10 06:28 UTC, deltamarnix commented on src/index.html
> +        <li><b>Assess</b>. Things to look at closely, but not necessarily trial yet — unless you think they would be a
Added

2024-06-10 06:52 UTC, joelvdberg submitted a review, later dismissed

2024-06-10 06:57 UTC, joelvdberg approved these changes

2024-06-10 06:57 UTC, merged